### ISSUE TITLE
[Feature] 能否恢复旧版本的战甲、武器模拟配卡模块

### ISSUE THREAD

**Issue by Excelsiorly** [Richasy/Wfa.Uwp#42]
### 问题描述

能否恢复旧版本的战甲、武器模拟配卡模块，挺好用的，但是现在没了

### 描述解决方案

恢复旧版本的战甲、武器模拟配卡模块

**Comment by Richasy** [comment]
武器或战甲配卡模块需要有极性以及mod数据支持，现有的在线数据库不足以做到这一点，我之前是逐一适配的，现在已经没有这个精力了
